#
# Oracle Java 8 Dockerfile
#
# https://github.com/dockerfile/java
# https://github.com/dockerfile/java/tree/master/oracle-java8
#

# Pull base image.
FROM java

ADD Scheduler.jar .

EXPOSE 8000

# Define default command.
CMD ["java", "-cp", "Scheduler.jar", "com.fakrudeen.scheduler.WebService", "8000"]
